<!-- Generated from content/profile.json and templates/README.en.md.tpl by scripts/build_readme.py. -->
<!-- Do not edit this file directly. -->

# {{ title }}

{{ headline }}

{{ badges }}

> {{ summary }}

## {{ projects_title }}

{{ projects }}

## {{ focus_title }}

{{ focus }}

## {{ connect_title }}

{{ connect }}

---

**{{ language_title }}**: [English](README.md) | [中文](README-zh.md)
